---

- hosts: default
  become: true
  vars_files: 
    - vars/main.yml
    
  roles:
    - role: zabbix
      tags: zabbix
      vars_files:
        - vars/main.yml
    - role: mysql
      tags: mysql
      vars_files:
        - vars/main.yml
  